import numpy as np

np.can_cast(np.int32, np.int64)
np.can_cast(np.float64, np.complex)
np.can_cast(np.complex, np.float)
np.can_cast('i8', 'f8')
np.can_cast('i8', 'f4')
np.can_cast('i4', 'S4')
np.can_cast(100, 'i1')
np.can_cast(150, 'i1')
np.can_cast(150, 'u1')
np.can_cast(3.5e100, np.float32)
np.can_cast(1000.0, np.float32)
np.can_cast(np.array(1000.0), np.float32)
np.can_cast(np.array([1000.0]), np.float32)
np.can_cast('i8', 'i8', 'no')
np.can_cast('<i8', '>i8', 'no')
np.can_cast('<i8', '>i8', 'equiv')
np.can_cast('<i4', '>i8', 'equiv')
np.can_cast('<i4', '>i8', 'safe')
np.can_cast('<i8', '>i4', 'safe')
np.can_cast('<i8', '>i4', 'same_kind')
np.can_cast('<i8', '>u4', 'same_kind')
np.can_cast('<i8', '>u4', 'unsafe')
